// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQKyOHt6Ve1_RQcxFrWfFuSBpWCgqTn1o',
    appId: '1:51608623882:web:cdacf1d8a74455e6f0b8f3',
    messagingSenderId: '51608623882',
    projectId: 'my-id-24e41',
    authDomain: 'my-id-24e41.firebaseapp.com',
    storageBucket: 'my-id-24e41.firebasestorage.app',
    measurementId: 'G-7GHT4VZ1BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNB4RxbOtZQaU9aaXO9EIMg440Np6R2ko',
    appId: '1:51608623882:android:d4676837a79c082af0b8f3',
    messagingSenderId: '51608623882',
    projectId: 'my-id-24e41',
    storageBucket: 'my-id-24e41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxeyJeQJHxeFyTsbhfFQ-r4geF6BQAdy0',
    appId: '1:51608623882:ios:ca365452c1f9ef39f0b8f3',
    messagingSenderId: '51608623882',
    projectId: 'my-id-24e41',
    storageBucket: 'my-id-24e41.firebasestorage.app',
    iosBundleId: 'com.example.myCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxeyJeQJHxeFyTsbhfFQ-r4geF6BQAdy0',
    appId: '1:51608623882:ios:ca365452c1f9ef39f0b8f3',
    messagingSenderId: '51608623882',
    projectId: 'my-id-24e41',
    storageBucket: 'my-id-24e41.firebasestorage.app',
    iosBundleId: 'com.example.myCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQKyOHt6Ve1_RQcxFrWfFuSBpWCgqTn1o',
    appId: '1:51608623882:web:ab64d6f775b2b66ff0b8f3',
    messagingSenderId: '51608623882',
    projectId: 'my-id-24e41',
    authDomain: 'my-id-24e41.firebaseapp.com',
    storageBucket: 'my-id-24e41.firebasestorage.app',
    measurementId: 'G-534WFBGK8W',
  );
}
